flowchart LR
    A["Butler Python\nclient library"] --> B["Rubin Science Platform\nHTTP Ingress"]
    A <--> C[("S3 Bucket\n(Datastore)")]
    D[("S3 Bucket\n(Query Results)")] --> A
    B --> E[Butler Server]
    E --> F[(Redis)]
    E --> G[("Postgres DB\nPrimary")]
    G --> H[("Postgres DB\nReplicas")]
    F <--> I[Query workers]
    I --> H
    I --> D
    

  